# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "lxloexa-hwb72332"
user = "snowtrial001"
password = "Snowtrial123!"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "HOL_SCHEMA"